services:
  backend:
    build: ./backend
    container_name: mnist-backend
    networks:
      - app-network
    command: uvicorn server:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: mnist-frontend
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: mnist-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge 